# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontdssl
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backdssl
      dockerfile: Dockerfile
    ports:
      - "3300:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=bddssl
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=tiendavirtual
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge